# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2f2d8c80cb04cfec67d0d429a64d5bdb2733bf6ac846e71ec04169cec981f3b2febf1cf2b493718a748eeb45899e509c3cb45ec18544359d217c192939c7a2d

test:
  secret_key_base: 29eb25a42d138baee82218a26afbfc8ff2ef7e74e458bada61bb0b1c92153390056e314e252f2483669b283978a26e0257f7f122f26f3f052832ec7a6bf2f228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
